### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by rszeto** [rubenvillegas/iclr2017mcnet#1]
Hi Ruben,

I would like to recommend adding a few dependencies that were not mentioned in the main README file:

```
# Needed to run test code
pip install opencv-python
# Needed to download Sports1M
pip install pytube
# Needed to extract UCF-100
sudo apt-get install unrar
```

The command to extract the UCF-100 .rar file may be helpful as well:

```
unrar x UCF101.rar
```

Finally, instructions on reading the .npz files would be useful:

```python
import numpy as np
a = np.load('results_model=MCNET.model-102502.npz')
print(a['psnr'])
print(a['ssim'])
```

**Comment by rubenvillegas** [comment]
Thank you very much for your suggestions! I will update these.

**Comment by rszeto** [comment]
Another dependency (needed to run KTH training):

```
pip install joblib
```

**Comment by rubenvillegas** [comment]
Updated the README.md file. I will update about loading the results file by the weekend. Thank you very much!
