### ISSUE TITLE
Could you suggest me an approach for working with MCNet on a Custom Data

### ISSUE THREAD

**Issue by sharathyadav1993** [rubenvillegas/iclr2017mcnet#13]
Hi Ruben,

Thank you for the MCNet code. I want to use your MCNet for video frame extrapolation task for my custom dataset. It would be great if you suggest me some approach in doing it, or share me some generalized code to work for my dataset.

Regards
Sharath

**Comment by rubenvillegas** [comment]
Hi Sharath,

If you look at the file ./src/utils.py, there are functions to load each dataset (e.g., load_kth_data). You should add another function to load your specific dataset, and follow the same input/output scheme. Hope this helps.


Regards,
Ruben
