### ISSUE TITLE
pre_trained model

### ISSUE THREAD

**Issue by lihaolin1** [rubenvillegas/iclr2017mcnet#16]
Hello, I think the pre-trained model already been removed, every time when I run "./models/paper_models/download.sh" it always gives me a 403 forbidden error.

**Comment by rubenvillegas** [comment]
The models were stored in my MBox account but since I graduated they discontinued it. There models are now here: https://drive.google.com/drive/folders/15OvDikL6riJJ_hhrKN50msR06HkzIzsb?usp=sharing
