### ISSUE TITLE
gdl loss

### ISSUE THREAD

**Issue by kikyou123** [rubenvillegas/iclr2017mcnet#5]

**Comment by kikyou123** [comment]
what the UCF-101 dataset ？

**Comment by rubenvillegas** [comment]
Did you figure out the reason of the shapes in the first issue? It seems like it disappeared from the thread.
I don't understand the second question.

**Comment by kikyou123** [comment]
the first issure i have solved. the second issure i am asking why the train script don not have UCF-101 datasets?

**Comment by rubenvillegas** [comment]
Because the qualitative results shown in the paper are from training on Sports 1M and testing on UCF101. We found that numerically it gives very similar results, thus the generalizability of our method.

**Comment by kikyou123** [comment]
thank you for your replay. i understand it
