### ISSUE TITLE
Evaluating trained model with KTH fails

### ISSUE THREAD

**Issue by kikyou123** [rubenvillegas/iclr2017mcnet#6]
when i run test_kth.py, it is show AttributeError: 'module' object has no attribute 'compute_ssim'. it seems 
![image](https://user-images.githubusercontent.com/19486038/29602827-5054086e-8814-11e7-9a09-2601586673ec.png)
something is wrong with it

**Comment by rubenvillegas** [comment]
Did you install pyssim?

"""
pip install pyssim
"""

If you did, then it's a problem of the version.

**Comment by kikyou123** [comment]
thanks for you replay, i install pyssim, and i solved it！！
