### ISSUE TITLE
About another paper

### ISSUE THREAD

**Issue by kikyou123** [rubenvillegas/iclr2017mcnet#7]
It is a wonderful work! I notice another paper "Learning to Generate Long-term Future via Hierarchical Prediction" is your job, too. But you don't release code for that paper. Will you release in the future? If you will, can you release it as soon as possible? Or can you just tell me how you process the  Penn Action dataset in that paper?

**Comment by rubenvillegas** [comment]
Sorry for the very delayed response. I have been busy with other research. I have received requests for the code to that paper so I will try to get the code release as soon as possible.

**Comment by rubenvillegas** [comment]
Here's the code:
https://github.com/rubenvillegas/icml2017hierchvid
